### ISSUE TITLE
Error with ProjectConfig after settings changed

### ISSUE THREAD

**Issue by JonnyBR12** [riasvdv/craft-scout#152]
Hey @riasvdv 

We had Scout working fine but after unticking 'Sync' in the CMS settings, we now get the following error below. Have you seen this before?

Only way to get back in the CMS is to remove the Scout line from phpMyAdmin. Then, I remove it from the plugins list but when installing again, I get the same issue. I'm using the set-up file as per the docs that was working initially with the correct channels. 

If you can point me in the right direction, that would be great. 

Craft CMS 3.4.11, PHP 7.3

PHP Notice – yii\base\ErrorException Undefined offset: 1
vendor/craftcms/cms/src/helpers/ProjectConfig.php line 275

<img width="751" alt="Screenshot 2020-03-30 at 17 44 34" src="https://user-images.githubusercontent.com/654547/77938783-22af2100-72ae-11ea-9230-4efe00882fb1.png">

**Comment by joshangell** [comment]
I hit this issue as well on a live site (doh), to fix it for me I removed all the rows from the `projectconfig` table that had a `path` starting with `plugins.scout.settings`.

I’m going to debug it locally now and see if I can reproduce it at all ...

**Comment by JonnyBR12** [comment]
Ha, yeah I did the same thing just earlier and not long re-installed - I think we had almost 300 rows in there in the projectconfig table. I found it out by searching the database for any mentions of 'scout'.

**Comment by martinhellwagner** [comment]
Same thing happening to my – only on my local environment though.

**Comment by martinhellwagner** [comment]
@timkelty 

Any news on this? It's turning out to be a major problem on our systems because it renders every environment unusable after each deploy – we have to fix it manually by editing the Craft CMS source code in the `ProjectConfig.php` file in the vendor folder.

**Comment by martinhellwagner** [comment]
@timkelty 
@riasvdv 

Checking in again on this issue – any news?

**Comment by rianconley** [comment]
@timkelty
@riasvdv

I'm having the same issue with this plugin. I tried completely removing it and then re-installing it but the error persists.

**Comment by tehtrav** [comment]
Same thing happened to me. My local site completely died after I clicked "Save" in the Scout settings control panel.

**Comment by leevigraham** [comment]
+1… just got bitten by this.

**Comment by martinhellwagner** [comment]
@timkelty 
@riasvdv 

Can you already provide an update for this? This issue is open for over 2 months and multiple people are affected by it. 🤔

**Comment by timkelty** [comment]
Here's how I could get it back locally after saving settings in the CP:

Truncate the project config table TRUNCATE TABLE craft_projectconfig;
delete the entire plugins.scout.settings node in your project.yaml
Clear caches. Note - you may have to do this manually if you craft command is still throwing errors. In my case I had to restart my redis container. If you're using the default file cache, delete your storage folder.
run craft project-config/sync --force
You should be back running, just don't save Scout settings from the CP or it will happen again.

Since a config/scout.php is already required for indices…I'm considering just dropping CP settings all together. Really the only thing you might want to do on a whim is toggle sync, but you could effectively do that by just disabling Scout as well…

**Comment by brandonkelly** [comment]
The way Scout 2 is storing nested objects in its field settings would have been problematic even before project config.

I’ve just submitted riasvdv/craft-scout#162 which should fix this error going forward.

**Comment by sidoneill** [comment]
@ryanirelan (and anyone else who, like me, was still having an issue even with the new release) the issue likely that you still have the offending nested objects stored in your projectconfig table. Look for and delete the plugins.scout.settings rows and you should be good to go (and no longer sweating every update).

**Comment by davidhellmann** [comment]
Wow, Installed the Scout Plugin and kills my entire ENV. Not funny. Any Ideas if there a solution for this problems?

**Comment by timkelty** [comment]
@davidhellmann with this same error?

**Comment by davidhellmann** [comment]
Hey @timkelty 

yes with the `Undefined offset: 1` error.
